<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_2_Services</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\ValidationHelpers\**" />
    <EmbeddedResource Remove="Helpers\ValidationHelpers\**" />
    <None Remove="Helpers\ValidationHelpers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\1-Repository\1-Repository.csproj" />
  </ItemGroup>

</Project>
